### ISSUE TITLE
No module named 'mmpose.models.registry'

### ISSUE THREAD

**Issue by mathpopo** [HRNet/Lite-HRNet#40]
(base) chenxin@chenxin-Nitro-AN515-52:~/disk1/github/Lite-HRNet/mmpose/mmpose/models$ tree .
.
├── backbones
│   ├── alexnet.py
│   ├── base_backbone.py
│   ├── cpm.py
│   ├── hourglass.py
│   ├── hrnet.py
│   ├── __init__.py
│   ├── mobilenet_v2.py
│   ├── mobilenet_v3.py
│   ├── mspn.py
│   ├── regnet.py
│   ├── resnest.py
│   ├── resnet.py
│   ├── resnext.py
│   ├── rsn.py
│   ├── scnet.py
│   ├── seresnet.py
│   ├── seresnext.py
│   ├── shufflenet_v1.py
│   ├── shufflenet_v2.py
│   ├── tcn.py
│   ├── utils
│   │   ├── channel_shuffle.py
│   │   ├── __init__.py
│   │   ├── inverted_residual.py
│   │   ├── make_divisible.py
│   │   ├── se_layer.py
│   │   └── utils.py
│   └── vgg.py
├── builder.py
├── detectors
│   ├── associative_embedding.py
│   ├── base.py
│   ├── __init__.py
│   ├── interhand_3d.py
│   ├── mesh.py
│   ├── multi_task.py
│   ├── pose_lifter.py
│   └── top_down.py
├── heads
│   ├── ae_higher_resolution_head.py
│   ├── ae_simple_head.py
│   ├── deeppose_regression_head.py
│   ├── hmr_head.py
│   ├── __init__.py
│   ├── interhand_3d_head.py
│   ├── temporal_regression_head.py
│   ├── topdown_heatmap_base_head.py
│   ├── topdown_heatmap_multi_stage_head.py
│   └── topdown_heatmap_simple_head.py
├── __init__.py
├── losses
│   ├── classfication_loss.py
│   ├── __init__.py
│   ├── mesh_loss.py
│   ├── mse_loss.py
│   ├── multi_loss_factory.py
│   └── regression_loss.py
├── misc
│   ├── discriminator.py
│   └── __init__.py
├── necks
│   ├── gap_neck.py
│   └── __init__.py
└── utils
    ├── geometry.py
    ├── __init__.py
    └── ops.py

8 directories, 60 files

**Comment by IanUJo** [comment]
Modify it like this:

vi ./models/backbones/litehrnet.py
\# from mmpose.models.registry import BACKBONES
from mmpose.models import BACKBONES

vi ./models/builder.py
\# from mmpose.models.registry import BACKBONES, HEADS, LOSSES, NECKS, POSENETS
from mmpose.models import BACKBONES, HEADS, LOSSES, NECKS, POSENETS

The cause is probably because the location of the phrase is different depending on the version. If you use 0.14, the phrase exists in registry.py, and if you use 0.15, in builder.py.

**Comment by mathpopo** [comment]
@IanUJo ok thanks
